// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2129.PotSwitchWiperSample;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.TalonSRX;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static AnalogPotentiometer pIDWiperWiperPot;
    public static SpeedController pIDWiperWiperMotorController;
    //public static PIDController pIDWiperWiperPIDController;
    public static DigitalInput pIDWiperLeftLimitSwitch;
    public static DigitalInput pIDWiperRightLimitSwitch;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
    	//Preferences preferences = Preferences.getInstance();
    	//double safeMotorSpeed = preferences.getDouble("MotorSpeed", 0.3);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        pIDWiperWiperPot = new AnalogPotentiometer(0, 1.0, 0.0);
        LiveWindow.addSensor("PIDWiper", "WiperPot", pIDWiperWiperPot);
        
        pIDWiperWiperMotorController = new TalonSRX(4);
        LiveWindow.addActuator("PIDWiper", "WiperMotorController", (TalonSRX) pIDWiperWiperMotorController);
        
        //pIDWiperWiperPIDController = new PIDController(0.01, 0.0, 0.0, 0.0, pIDWiperWiperPot, pIDWiperWiperMotorController, 0.02);
        //LiveWindow.addActuator("PIDWiper", "WiperPIDController", pIDWiperWiperPIDController);
        //pIDWiperWiperPIDController.setContinuous(false);
        //pIDWiperWiperPIDController.setAbsoluteTolerance(0.2);

        //pIDWiperWiperPIDController.setOutputRange(-1.0, 1.0);
        pIDWiperLeftLimitSwitch = new DigitalInput(0);
        LiveWindow.addSensor("PIDWiper", "LeftLimitSwitch", pIDWiperLeftLimitSwitch);
        
        pIDWiperRightLimitSwitch = new DigitalInput(1);
        LiveWindow.addSensor("PIDWiper", "RightLimitSwitch", pIDWiperRightLimitSwitch);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
