// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2129.PotSwitchWiperSample;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.TalonSRX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DigitalInput wiperLeftLimitSwitch;
    public static DigitalInput wiperRightLimitSwitch;
    public static AnalogPotentiometer wiperWiperAnglePot;
    public static SpeedController wiperwiperMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        wiperLeftLimitSwitch = new DigitalInput(0);
        LiveWindow.addSensor("Wiper", "LeftLimitSwitch", wiperLeftLimitSwitch);
        
        wiperRightLimitSwitch = new DigitalInput(1);
        LiveWindow.addSensor("Wiper", "RightLimitSwitch", wiperRightLimitSwitch);
        
        wiperWiperAnglePot = new AnalogPotentiometer(0, 1.0, 0.0);
        LiveWindow.addSensor("Wiper", "WiperAnglePot", wiperWiperAnglePot);
        
        wiperwiperMotor = new TalonSRX(4);
        LiveWindow.addActuator("Wiper", "wiperMotor", (TalonSRX) wiperwiperMotor);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
