// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2129.PotSwitchWiperSample.subsystems;

import org.usfirst.frc2129.PotSwitchWiperSample.Robot;
import org.usfirst.frc2129.PotSwitchWiperSample.RobotMap;
import org.usfirst.frc2129.PotSwitchWiperSample.commands.*;
import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Wiper extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DigitalInput leftLimitSwitch = RobotMap.wiperLeftLimitSwitch;
    private final DigitalInput rightLimitSwitch = RobotMap.wiperRightLimitSwitch;
    private final AnalogPotentiometer wiperAnglePot = RobotMap.wiperWiperAnglePot;
    private final SpeedController wiperMotor = RobotMap.wiperwiperMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public boolean getLeftLimitSwitchStatus()
    {
    	return leftLimitSwitch.get();
    }
    
    public boolean getRightLimitSwitchStatus()
    {
    	return rightLimitSwitch.get();
    }
    
    public double getAnglePotValue()
    {
    	return wiperAnglePot.get();
    }

	public void swipeLeft(double speed) {
		wiperMotor.set(speed);
	}
	
	public void swipeRight( double speed ) {
		wiperMotor.set(0 - speed);
	}

	public void stopSwipe() {
		wiperMotor.set(0);
		
	}

	public void updateSmartdashboard() {
    	SmartDashboard.putBoolean("Left Limit Switch", Robot.wiper.getLeftLimitSwitchStatus());
    	SmartDashboard.putBoolean("Right Limit Switch", Robot.wiper.getRightLimitSwitchStatus());
    	SmartDashboard.putNumber("Wiper Potentiometer", Robot.wiper.getAnglePotValue());		
	}
}

